alg_items = [
    "Algebra Diagnostics Practice Set",
    "Algebraic Manipulation Exercise",
    "Algebraic Manipulation Practice Set",
    "Forms of Linear Equations Exercise",
    "Slope Exercise",
    "Solving for X Exercise",
    "Linear Equations Practice Set",
    "Graphs of Linear Equations Exercise",
    "The Slope Exercises",
    "Intercepts Exercise",
    "Graphs of Linear Equations Practice Set",
    "Linear Modeling Exercise",
    "Linear Modeling Practice Set",
    "Systems of Linear Equations Exercise",
    "Systems of Linear Equations Practice Set",
    "Word Problems Exercise",
    "Linear Inequalities Exercise",
    "Solutions to a Linear Inequality Exercise",
    "Linear Inequalities Practice Set",
    "Graphs and Systems of Linear Inequalities Exercise",
    "Systems of Linear Inequalities Exercise",
    "Graphs and Systems of Linear Inequalities Practice Set",
    "Absolute Value Exercise",
    "Absolute Value Inequalities Exercise",
    "Absolute Value Practice Set"
]


adv_items = [
    "Advanced Math Diagnostic Practice Set",
    "Polynomial Expressions Exercises",
    "Polynomial Expressions Practice Set",
    "Quadratic Equations Exercises",
    "Solving Quadratic Equations Exercise",
    "Solving by Factoring Exercise",
    "Solving Using the Quadratic Formula Exercise",
    "Quadratic Equations Practice Set",
    "Quadratic Modeling Exercise",
    "Height vs Time Exercise",
    "Quadratic Modeling Practice Set",
    "Exponents and Radicals Exercise",
    "Exponents and Radicals Practice Set",
    "Rational Functions Exercise",
    "Solving Rational Functions Exercise",
    "Rational Functions Practice Set",
    "Linear-Quadratic Systems of Equations Exercise",
    "Linear-Quadratic Systems of Equations Practice Set",
    "Linear and Exponential Growth Exercise",
    "Linear and Exponential Growth Practice Set",
    "Graph of Nonlinear Equations Exercise",
    "Quadratic Graphs Exercise",
    "Exponential Graphs Exercise",
    "Graphs of Nonlinear Equations Practice Set",
    "Functions and Function Notation Exercise",
    "Functions and Function Notation Practice Set"
]

psda_items = [
    "Problem Solving and Data Analysis Diagnostic",
    "Ratios Exercises",
    "Proportions Exercise",
    "Rates Exercise",
    "Ratios, Proportions, and Rates Practice Set",
    "Percentages Exercise",
    "Percentage Change Exercise",
    "Percentages Practice Set",
    "Measurements and Unit Conversion Exercise",
    "Unit Conversions with Rates Exercise",
    "Measure and Unit Conversion Practice Set",
    "Statistics Exercise",
    "Statistics Practice Set",
    "Graphical Displays of Statistics Exercise",
    "Bar Graphs Exercise",
    "Line Graphs Exercise",
    "Scatterplots Exercise",
    "Graphical Displays of Statistics Practice Set",
    "Probability and Conditional Probability Exercise",
    "Missing Values Exercise",
    "Data Inferences Exercise",
    "Data Inference Practice Set Practice Set"
]

gtrig_items = [
    "Geometry Diagnostics Practice Set",
    "Area and Volume Exercise",
    "Area and Volume Practice Set",
    "Angle Relationships Exercise",
    "Triangle Properties Exercise",
    "Angles, Similarity, and Triangles Practice Set",
    "Right Triangle Trigonometry Exercise",
    "Special Right Triangles Exercise",
    "Right Triangle Trigonometry Practice Set",
    "Radians and Degrees Exercise",
    "Unit Circle Trigonometry Exercise",
    "Radians and Degrees Practice Set",
    "Circle Equations Exercise",
    "Circle Equations Practice Set",
    "Circle Theorems Exercise",
    "Circle Theorems Practice Set"
]


alg_new_mergeList = [
    "Algebra Diagnostics Title Page.pdf",
    "Algebra Diagnostics Practice Set.pdf",
    "Algebraic Manipulation.pdf",
    "Algebraic Manipulation Exercise.pdf",
    "Algebraic Manipulation Practice Set.pdf",
    "Forms of Linear Equations.pdf",
    "Forms of Linear Equations Exercise.pdf",
    "Finding the Slope.pdf",
    "Finding the Slope Pt 2.pdf",
    "Slope Exercise.pdf",
    "Linear Equations Solving for X.pdf",
    "Linear Equations Solving for X Pt 2.pdf",
    "Solving for X Exercise.pdf",
    "Linear Equations Practice Set.pdf",
    "Graphs of Linear Functions.pdf",
    "Graphs of Linear Functions Pt 2.pdf",
    "Graphs of Linear Equations Exercise.pdf",
    "Graphs of Linear Equations Slope.pdf",
    "Graphs of Linear Equations Slope Pt 2.pdf",
    "Graphs of Linear Equations Slope Pt 3.pdf",
    "The Slope Exercises.pdf",
    "Finding the Intercept.pdf",
    "Intercepts Exercise.pdf",
    "Graphs of Linear Equations Practice Set.pdf",
    "Linear Modeling.pdf",
    "Linear Modeling Exercise.pdf",
    "Linear Modeling Practice Set.pdf",
    "Systems of Linear Equations.pdf",
    "Systems of Linear Equations Exercise.pdf",
    "Systems of Linear Equations Practice Set.pdf",
    "Word Problems.pdf",
    "Word Problems Exercise.pdf",
    "Linear Inequalities.pdf",
    "Linear Inequalities Exercise.pdf",
    "Linear Inequalities Finding the Solution.pdf",
    "Solutions to a Linear Inequality Exercise.pdf",
    "Linear Inequalities Practice Set.pdf",
    "Graphs and Systems of Linear Inequalities.pdf",
    "Graphs and Systems of Linear Inequalities Exercise.pdf",
    "Systems of Linear Inequalities.pdf",
    "Systems of Linear Inequalities Exercise.pdf",
    "Graphs and Systems of Linear Inequalities Practice Set.pdf",
    "Absolute Value.pdf",
    "Absolute Value Exercise.pdf",
    "Absolute Value Inequalities.pdf",
    "Absolute Value Inequalities Exercise.pdf",
    "Absolute Value Practice Set.pdf"
]

adv_mergeList = [
    "Advanced Math Diagnostics Title Page.pdf",
    "Advanced Math Diagnostic Practice Set.pdf",
    "Polynomial Expressions.pdf",
    "Polynomial Expressions Exercises.pdf",
    "Polynomial Expressions Practice Set.pdf",
    "Quadratic Equations.pdf",
    "Quadratic Equations Exercises.pdf",
    "Solving Quadratic Equations Exercise.pdf",
    "Solving by Factoring.pdf",
    "Solving by Factoring Exercise.pdf",
    "Solving with the Quadratic Formula.pdf",
    "Solving Using the Quadratic Formula Exercise.pdf",
    "Quadratic Equations Practice Set.pdf",
    "Quadratic Modeling.pdf",
    "Quadratic Modeling Exercise.pdf",
    "Quadratic Modeling Height vs Time.pdf",
    "Height vs Time Exercise.pdf",
    "Quadratic Modeling Practice Set.pdf",
    "Exponents and Radicals.pdf",
    "Exponents and Radicals Exercise.pdf",
    "Exponents and Radicals Practice Set.pdf",
    "Rational Functions.pdf",
    "Rational Functions Exercise.pdf",
    "Solving Rational Equations.pdf",
    "Solving Rational Functions Exercise.pdf",
    "Rational Functions Practice Set.pdf",
    "Linear_Quadratic Systems of Equations.pdf",
    "Linear-Quadratic Systems of Equations Exercise.pdf",
    "Linear-Quadratic Systems of Equations Practice Set.pdf",
    "Linear_Exponential Growth Intro.pdf",
    "Exponential Growth.pdf",
    "Linear Growth.pdf",
    "Linear and Exponential Growth Exercise.pdf",
    "Linear and Exponential Growth Practice Set.pdf",
    "Nonlinear Graphs.pdf",
    "Graph of Nonlinear Equations Exercise.pdf",
    "Quadratic Graphs.pdf",
    "Quadratic Graphs Exercise.pdf",
    "Exponential Graphs.pdf",
    "Exponential Graphs Exercise.pdf",
    "Graphs of Nonlinear Equations Practice Set.pdf",
    "Functions and Function Notation.pdf",
    "Functions and Function Notation Exercise.pdf",
    "Functions and Function Notation Practice Set.pdf"
]

psda_mergeList = [
    "Problem Solving and Data Analysis Diagnostics.pdf",
    "Problem Solving and Data Analysis Diagnostic.pdf",
    "Ratios.pdf",
    "Ratios Exercises.pdf",
    "Proportions.pdf",
    "Proportions Exercise.pdf",
    "Rates.pdf",
    "Rates Exercise.pdf",
    "Ratios, Proportions, and Rates Practice Set.pdf",
    "Percentages.pdf",
    "Percentages Pt 2.pdf",
    "Percentages Exercise.pdf",
    "Percent Change.pdf",
    "Percentage Change Exercise.pdf",
    "Percentages Practice Set.pdf",
    "Measurements and Unit Conversion.pdf",
    "Measurements and Unit Conversion Exercise.pdf",
    "Unit Conversion with Rates.pdf",
    "Unit Conversions with Rates Exercise.pdf",
    "Measure and Unit Conversion Practice Set.pdf",
    "Statistics and Probability.pdf",
    "Calculating a Missing Value.pdf",
    "Statistics Exercise.pdf",
    "Statistics Practice Set.pdf",
    "Graphical Displays of Statistics.pdf",
    "Graphical Displays of Statistics Exercise.pdf",
    "Bar Graphs.pdf",
    "Bar Graphs Exercise.pdf",
    "Line Graphs.pdf",
    "Line Graphs Exercise.pdf",
    "Scatterplots.pdf",
    "Scatterplots Pt 2.pdf",
    "Scatterplots Exercise.pdf",
    "Graphical Displays of Statistics Practice Set.pdf",
    "Probability and Conditional Probability.pdf",
    "Probability and Conditional Probability Exercise.pdf",
    "Conditional Tables Missing Values.pdf",
    "Missing Values Exercise.pdf",
    "Data Inferences.pdf",
    "Data Inferences Exercise.pdf",
    "Margin of Error.pdf",
    "Data Inference Practice Set Practice Set.pdf"
]

gtrig_mergeList = [
    "Geometry Diagnostics Title Page.pdf",
    "Geometry Diagnostics Practice Set.pdf",
    "Area and Volume.pdf",
    "Area and Volume Exercise.pdf",
    "Area and Volume Practice Set.pdf",
    "Angles, Similarity, and Triangles.pdf",
    "Angle Relationships.pdf",
    "Angle Relationships Pt 2.pdf",
    "Angle Relationships Exercise.pdf",
    "Triangle Properties.pdf",
    "Triangle Properties Exercise.pdf",
    "Angles, Similarity, and Triangles Practice Set.pdf",
    "Right Triangle Trigonometry.pdf",
    "Right Triangle Trigonometry Exercise.pdf",
    "Special Right Triangles.pdf",
    "Special Right Triangles Exercise.pdf",
    "Right Triangle Trigonometry Practice Set.pdf",
    "Radians and Degrees.pdf",
    "Radians and Degrees Exercise.pdf",
    "Unit Circle Trigonometry.pdf",
    "Unit Circle Trigonometry Exercise.pdf",
    "Radians and Degrees Practice Set.pdf",
    "Circle Equations.pdf",
    "Circle Equations Exercise.pdf",
    "Manipulating Circle Equations.pdf",
    "Circle Equations Practice Set.pdf",
    "Circle Theorems.pdf",
    "Circle Theorems Exercise.pdf",
    "Circle Theorems Practice Set.pdf"
]

from transcription_helpers import * 
from transcription_data import * 
from regex_stuff import * 

alg_mergeList_updated= [
    "alg_newPDF/Algebra Diagnostics Title Page.pdf",
    "alg_exPset/Algebra Diagnostics Practice Set.pdf",
    "alg_newPDF/Algebraic Manipulation.pdf",
    "alg_exPset/Algebraic Manipulation Exercise.pdf",
    "alg_exPset/Algebraic Manipulation Practice Set.pdf",
    "alg_newPDF/Forms of Linear Equations.pdf",
    "alg_exPset/Forms of Linear Equations Exercise.pdf",
    "alg_newPDF/Finding the Slope.pdf",
    "alg_newPDF/Finding the Slope Pt 2.pdf",
    "alg_exPset/Slope Exercise.pdf",
    "alg_newPDF/Linear Equations Solving for X.pdf",
    "alg_newPDF/Linear Equations Solving for X Pt 2.pdf",
    "alg_exPset/Solving for X Exercise.pdf",
    "alg_exPset/Linear Equations Practice Set.pdf",
    "alg_newPDF/Graphs of Linear Functions.pdf",
    "alg_exPset/Graphs of Linear Equations Exercise.pdf",
    "alg_newPDF/Graphs of Linear Equations Slope.pdf",
    "alg_newPDF/Graphs of Linear Equations Slope Pt 2.pdf",
    "alg_newPDF/Graphs of Linear Equations Slope Pt 3.pdf",
    "alg_exPset/The Slope Exercises.pdf",
    "alg_newPDF/Finding the Intercept.pdf",
    "alg_exPset/Intercepts Exercise.pdf",
    "alg_exPset/Graphs of Linear Equations Practice Set.pdf",
    "alg_newPDF/Linear Modeling.pdf",
    "edited_grouped_questions/Linear Modeling Exercise_edited.pdf",
    "alg_exPset/Linear Modeling Practice Set.pdf",
    "alg_newPDF/Systems of Linear Equations.pdf",
    "alg_exPset/Systems of Linear Equations Exercise.pdf",
    "alg_exPset/Systems of Linear Equations Practice Set.pdf",
    "alg_newPDF/Word Problems.pdf",
    "edited_grouped_questions/Word Problems Exercise_edited.pdf",
    "alg_newPDF/Linear Inequalities.pdf",
    "alg_exPset/Linear Inequalities Exercise.pdf",
    "alg_newPDF/Linear Inequalities Finding the Solution.pdf",
    "edited_grouped_questions/Solutions to a Linear Inequality Exercise_edited.pdf",
    "alg_exPset/Linear Inequalities Practice Set.pdf",
    "alg_newPDF/Graphs and Systems of Linear Inequalities.pdf",
    "alg_exPset/Graphs and Systems of Linear Inequalities Exercise.pdf",
    "alg_newPDF/Systems of Linear Inequalities.pdf",
    "alg_exPset/Systems of Linear Inequalities Exercise.pdf",
    "alg_exPset/Graphs and Systems of Linear Inequalities Practice Set.pdf",
    "alg_newPDF/Absolute Value.pdf",
    "alg_exPset/Absolute Value Exercise.pdf",
    "alg_newPDF/Absolute Value Inequalities.pdf",
    "alg_exPset/Absolute Value Inequalities Exercise.pdf",
    "alg_exPset/Absolute Value Practice Set.pdf"
]

adv_mergeList_updated = [
    "adv_math_newPDF/Advanced Math Diagnostics Title Page.pdf",
    "adv_math_exPset/Advanced Math Diagnostic Practice Set.pdf",
    "adv_math_newPDF/Polynomial Expressions.pdf",
    "adv_math_exPset/Polynomial Expressions Exercises.pdf",
    "adv_math_exPset/Polynomial Expressions Practice Set.pdf",
    "adv_math_newPDF/Quadratic Equations.pdf",
    "adv_math_exPset/Quadratic Equations Exercises.pdf",
    "adv_math_exPset/Solving Quadratic Equations Exercise.pdf",
    "adv_math_newPDF/Solving by Factoring.pdf",
    "adv_math_exPset/Solving by Factoring Exercise.pdf",
    "adv_math_newPDF/Solving with the Quadratic Formula.pdf",
    "adv_math_exPset/Solving Using the Quadratic Formula Exercise.pdf",
    "adv_math_exPset/Quadratic Equations Practice Set.pdf",
    "adv_math_newPDF/Quadratic Modeling.pdf",
    "adv_math_exPset/Quadratic Modeling Exercise.pdf",
    "adv_math_newPDF/Quadratic Modeling Height vs Time.pdf",
    "adv_math_exPset/Height vs Time Exercise.pdf",
    "adv_math_exPset/Quadratic Modeling Practice Set.pdf",
    "adv_math_newPDF/Exponents and Radicals.pdf",
    "adv_math_exPset/Exponents and Radicals Exercise.pdf",
    "adv_math_exPset/Exponents and Radicals Practice Set.pdf",
    "adv_math_newPDF/Rational Functions.pdf",
    "adv_math_exPset/Rational Functions Exercise.pdf",
    "adv_math_newPDF/Solving Rational Equations.pdf",
    "adv_math_exPset/Solving Rational Functions Exercise.pdf",
    "adv_math_exPset/Rational Functions Practice Set.pdf",
    "adv_math_newPDF/Linear_Quadratic Systems of Equations.pdf",
    "adv_math_exPset/Linear-Quadratic Systems of Equations Exercise.pdf",
    "adv_math_exPset/Linear-Quadratic Systems of Equations Practice Set.pdf",
    "adv_math_newPDF/Linear_Exponential Growth Intro.pdf",
    "adv_math_newPDF/Exponential Growth.pdf",
    "adv_math_newPDF/Linear Growth.pdf",
    "adv_math_exPset/Linear and Exponential Growth Exercise.pdf",
    "adv_math_exPset/Linear and Exponential Growth Practice Set.pdf",
    "adv_math_newPDF/Nonlinear Graphs.pdf",
    "adv_math_exPset/Graph of Nonlinear Equations Exercise.pdf",
    "adv_math_newPDF/Quadratic Graphs.pdf",
    "adv_math_exPset/Quadratic Graphs Exercise.pdf",
    "adv_math_newPDF/Exponential Graphs.pdf",
    "adv_math_exPset/Exponential Graphs Exercise.pdf",
    "adv_math_exPset/Graphs of Nonlinear Equations Practice Set.pdf",
    "adv_math_newPDF/Functions and Function Notation.pdf",
    "adv_math_exPset/Functions and Function Notation Exercise.pdf",
    "adv_math_exPset/Functions and Function Notation Practice Set.pdf"
]

psda_mergeList_updated = [
    "PSDA_newPDF/Problem Solving and Data Analysis Diagnostics.pdf",
    "PSDA_exPset/Problem Solving and Data Analysis Diagnostic.pdf",
    "PSDA_newPDF/Ratios.pdf",
    "edited_grouped_questions/Ratios Exercise_edited.pdf",
    "PSDA_newPDF/Proportions.pdf",
    "edited_grouped_questions/Proportions Exercise_edited.pdf",
    "PSDA_newPDF/Rates.pdf",
    "edited_grouped_questions/Rates Exercise_edited.pdf",
    "PSDA_exPset/Ratios, Proportions, and Rates Practice Set.pdf",
    "PSDA_newPDF/Percentages.pdf",
    "PSDA_exPset/Percentages Exercise.pdf",
    "PSDA_newPDF/Percent Change.pdf",
    "PSDA_exPset/Percentage Change Exercise.pdf",
    "PSDA_exPset/Percentages Practice Set.pdf",
    "PSDA_newPDF/Measurements and Unit Conversion.pdf",
    "PSDA_exPset/Measurements and Unit Conversion Exercise.pdf",
    "PSDA_newPDF/Unit Conversion with Rates.pdf",
    "PSDA_exPset/Unit Conversions with Rates Exercise.pdf",
    "PSDA_exPset/Measure and Unit Conversion Practice Set.pdf",
    "PSDA_newPDF/Statistics and Probability.pdf",
    "PSDA_newPDF/Calculating a Missing Value.pdf",
    "PSDA_exPset/Statistics Exercise.pdf",
    "PSDA_exPset/Statistics Practice Set.pdf",
    "PSDA_newPDF/Graphical Displays of Statistics.pdf",
    "PSDA_exPset/Graphical Displays of Statistics Exercise.pdf",
    "PSDA_newPDF/Bar Graphs.pdf",
    "PSDA_exPset/Bar Graphs Exercise.pdf",
    "PSDA_newPDF/Line Graphs.pdf",
    "edited_grouped_questions/Line Graphs Exercise_edited.pdf",
    "PSDA_newPDF/Scatterplots.pdf",
    "PSDA_newPDF/Scatterplots Pt 2.pdf",
    "edited_grouped_questions/Scatterplots Exercise_edited.pdf",
    "PSDA_exPset/Graphical Displays of Statistics Practice Set.pdf",
    "PSDA_newPDF/Probability and Conditional Probability.pdf",
    "edited_grouped_questions/Probability and Conditional Probability Exercise_edited.pdf",
    "PSDA_newPDF/Conditional Tables Missing Values.pdf",
    "PSDA_exPset/Missing Values Exercise.pdf",
    "PSDA_newPDF/Data Inferences.pdf",
    "edited_grouped_questions/Data Inferences Exercise_edited.pdf",
    "PSDA_newPDF/Margin of Error.pdf",
    "PSDA_exPset/Data Inference Practice Set Practice Set.pdf"
]

gtrig_mergeList_updated = [
    "geom_newPDF/Geometry Diagnostics Title Page.pdf",
    "geom_exPset/Geometry Diagnostics Practice Set.pdf",
    "geom_newPDF/Area and Volume.pdf",
    "edited_grouped_questions/Area and Volume Exercise_edited.pdf",
    "geom_exPset/Area and Volume Practice Set.pdf",
    "geom_newPDF/Angles, Similarity, and Triangles.pdf",
    "geom_newPDF/Angle Relationships.pdf",
    "geom_newPDF/Angle Relationships Pt 2.pdf",
    "edited_grouped_questions/Angle Relationships Exercise_edited.pdf",
    "geom_newPDF/Triangle Properties.pdf",
    "edited_grouped_questions/Triangle Properties Exercise_edited.pdf",
    "geom_exPset/Angles, Similarity, and Triangles Practice Set.pdf",
    "geom_newPDF/Right Triangle Trigonometry.pdf",
    "geom_exPset/Right Triangle Trigonometry Exercise.pdf",
    "geom_newPDF/Special Right Triangles.pdf",
    "geom_exPset/Special Right Triangles Exercise.pdf",
    "geom_exPset/Right Triangle Trigonometry Practice Set.pdf",
    "geom_newPDF/Radians and Degrees.pdf",
    "geom_exPset/Radians and Degrees Exercise.pdf",
    "geom_newPDF/Unit Circle Trigonometry.pdf",
    "geom_exPset/Unit Circle Trigonometry Exercise.pdf",
    "geom_exPset/Radians and Degrees Practice Set.pdf",
    "geom_newPDF/Circle Equations.pdf",
    "geom_exPset/Circle Equations Exercise.pdf",
    "geom_newPDF/Manipulating Circle Equations.pdf",
    "geom_exPset/Circle Equations Practice Set.pdf",
    "geom_newPDF/Circle Theorems.pdf",
    "geom_exPset/Circle Theorems Exercise.pdf",
    "geom_exPset/Circle Theorems Practice Set.pdf"
]


diag_sheets = ["Advanced Math Diagnostic Practice Set",
               "Algebra Diagnostics Practice Set",
               "Algebraic Manipulation Exercise",
               "Problem Solving and Data Analysis Diagnostic",
               "Geometry Diagnostics Practice Set", 
               "Graphs of Linear Equations Practice Set", 
               "Systems of Linear Equations Practice Set",
               "Solutions to a Linear Inequality Exercise",
               "Intercepts Exercise",
               "Word Problems Exercise",
               "Linear Modeling Exercise",
               "Linear Modeling Practice Set",
               "Linear and Exponential Growth Practice Set",
               "Height vs Time Exercise",
               "Graphs of Nonlinear Equations Practice Set", 
               "Quadratic Equations Exercises", 
               "Quadratic Modeling Exercise",
               "Rational Functions Exercise",
               "Solving Rational Functions Exercise",
               "Ratios Exercises",
               "Proportions Exercise",
               "Rates Exercise",
               "Unit Conversions with Rates Exercise",
               "Statistics Exercise",
               "Bar Graphs Exercise",
               "Data Inference Practice Set Practice Set", 
               "Graphical Displays of Statistics Practice Set", 
               "Line Graphs Exercise", 
               "Missing Values Exercise", 
               "Probability and Conditional Probability Exercise",
               "Scatterplots Exercise",
               "Data Inferences Exercise",
               "Area and Volume Exercise",
               "Angle Relationships Exercise",
               "Triangle Properties Exercise",
               "Circle Theorems Exercise", 
               "Solving Rational Functions Exercise"]